### ISSUE TITLE
Fix as many Travis-CI build errors as possible for stackage release.

### ISSUE THREAD

**Issue by schell** [schell/steeloverseer#11]
Getting closer to stackage release, but still some errors:

https://travis-ci.org/schell/steeloverseer/builds/144231860

**Comment by mitchellwrosen** [comment]
Hmm... I just pushed some stuff to master 30ish mins ago. I wonder if my pushes don't trigger a build?

**Comment by schell** [comment]
I don't know what's up with that. I'm looking into it.

**Comment by mitchellwrosen** [comment]
Hm, well I see a build finally triggered, but maybe only because you pushed? Anyways, I'll fix those build errors soon
