### ISSUE TITLE
Crashes on emacs lock files. (symbolic link without a real target)

### ISSUE THREAD

**Issue by Prillan** [schell/steeloverseer#12]
While editing a file, emacs creates a lock file (symbolic link) of the form `.#filename → user@host.pid:timestamp` (not sure if it's a real timestamp or not).

While checking file status on files in the target directory, `sos` crashes with the following message:

```
sos: /path/to/file: getFileStatus: does not exist (No such file or directory)
```

Steps to reproduce:
1. Create an invalid link.
   
   ```
   $ cd /tmp
   $ ln -s /invalid/target link
   ```
2. Run `sos`
   
   ```
   $ sos .
   sos: /tmp/link: getFileStatus: does not exist (No such file or directory)
   ```

**Comment by schell** [comment]
That's interesting. Thanks for the report, I'll see what I can find.

**Comment by schell** [comment]
@Prillan - does it happen even when you specify a pattern (one that doesn't match the lock file)?

**Comment by Prillan** [comment]
It does. Minimal example:
```
$ ln -s /invalid/link link
$ sos -p very_random_pattern
Hit Ctrl+C to quit.
sos: /tmp/test/link: getFileStatus: does not exist (No such file or directory)
```

**Comment by mitchellwrosen** [comment]
This looks like an `fsnotify` bug

**Comment by mitchellwrosen** [comment]
@schell Can I get commit access to the repo?

**Comment by schell** [comment]
You should be good to go, @mitchellwrosen  - thanks 👍

**Comment by schell** [comment]
Yeah, that's odd - travis-ci says it's building my last commit.

**Comment by schell** [comment]
I'm on spacemacs now and this isn't happening. Methinks it's fixed?

**Comment by Prillan** [comment]
Try starting sos after emacs.

1. Navigate to a clean folder
2. Start emacs on a non-existing file `$ emacs asdf &`
3. Type some stuff in emacs, *do not save the file*.
4. Start sos

**Comment by schell** [comment]
Thanks for the update Prillan. Temporarily can you use a pattern that excludes those files? Something like `^[#]*otherstuff$`?

**Comment by Prillan** [comment]
I haven't needed to use the program for some time, so I'm fine for now.

**Comment by schell** [comment]
This doesn't crash for me, I see changes to these artifacts proc'ing if they are not excluded, which is expected.

**Comment by schell** [comment]
This only happens if you start `sos` in a directory where one of these files exists. If `sos` is started before that and _then_ emacs creates the lock file, everything is business as usual.
