### ISSUE TITLE
Megaparsec bound prevents building with stackage lts-7.x

### ISSUE THREAD

**Issue by NorfairKing** [schell/steeloverseer#17]
Aside from that: Amazing tool! I love it. Keep it up!

**Comment by schell** [comment]
Thanks, I'll get on this.

**Comment by schell** [comment]
@NorfairKing my guess is that this is only a problem with the version on hackage?

**Comment by NorfairKing** [comment]
@schell, I think so too. If you just have another stack file with lts-7.x and try it out, you should be able to find out.

**Comment by schell** [comment]
@NorfairKing newest `2.0.1.0` version is up on hackage. Let me know if it's still broken :)

**Comment by NorfairKing** [comment]
Seems to work. Thanks!!
