### ISSUE TITLE
Exclusion patterns

### ISSUE THREAD

**Issue by schell** [schell/steeloverseer#25]
It would be great to be able to exclude patterns explicitly so we don't have to model that with regular expressions. Excluding based on a string makes for a pretty tough regex.

```bash
sos -p ".*\.l?hs$" -e "#" -e "flycheck" -c "stack build"
```

This `sos` command would only `stack build` when changes are made to a haskell file (possibly literate haskell) that doesn't contain a `#` or `flymake`, which are both emacs artifacts.

**Comment by mitchellwrosen** [comment]
So flymake generates a file alongside the original, not tucked away in some special directory? As in,

```
- src/
  - src/Foo.hs
  - src/Foo_flymake.hs
```

or something?

**Comment by schell** [comment]
Yes - here's a play by play excerpt while working on varying:
```bash
schell~/D/c/varying:master$ sos -p ".*" -c "echo blah"
Hit Ctrl+C to quit.

Added: src/Control/Varying/.#Event.hs
[1/1] echo blah
blah
Success ✓

Added: src/Control/Varying/flycheck_Event.hs
[1/1] echo blah
blah
Success ✓

Added: src/Control/Varying/flycheck_Event.hs
[1/1] echo blah
blah
Success ✓

Added: src/Control/Varying/flycheck_Event.hs
[1/1] echo blah
blah
Success ✓
```

**Comment by mitchellwrosen** [comment]
Ok, just making sure this problem can't be solved by just picking a dir other than `.` to watch :)

Should be simple to add

**Comment by schell** [comment]
Totally - checking for `#` is pretty easy with character classes, but the `flycheck` string is trickier and really gunks up the watch regex.

**Comment by schell** [comment]
Works like a charm! Thanks @mitchellwrosen.
